# Form implementation generated from reading ui file 'd:\Dev\Python\pyQt\ZVA\zva.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(543, 218)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.instrBox = QtWidgets.QComboBox(parent=self.centralwidget)
        self.instrBox.setGeometry(QtCore.QRect(10, 30, 101, 22))
        self.instrBox.setObjectName("instrBox")
        self.pushButtonFindDevice = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButtonFindDevice.setGeometry(QtCore.QRect(10, 0, 101, 23))
        self.pushButtonFindDevice.setObjectName("pushButtonFindDevice")
        self.pushButtonConnect = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButtonConnect.setGeometry(QtCore.QRect(120, 0, 101, 23))
        self.pushButtonConnect.setObjectName("pushButtonConnect")
        self.textBrowser = QtWidgets.QTextBrowser(parent=self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(10, 60, 521, 111))
        self.textBrowser.setObjectName("textBrowser")
        self.pushButtonStart = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButtonStart.setGeometry(QtCore.QRect(400, 0, 75, 23))
        self.pushButtonStart.setObjectName("pushButtonStart")
        self.pushButtonSetup = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButtonSetup.setGeometry(QtCore.QRect(230, 0, 91, 23))
        self.pushButtonSetup.setObjectName("pushButtonSetup")
        self.deviceBox = QtWidgets.QComboBox(parent=self.centralwidget)
        self.deviceBox.setGeometry(QtCore.QRect(120, 30, 101, 22))
        self.deviceBox.setObjectName("deviceBox")
        self.timeEdit = QtWidgets.QTimeEdit(parent=self.centralwidget)
        self.timeEdit.setGeometry(QtCore.QRect(230, 30, 91, 22))
        self.timeEdit.setObjectName("timeEdit")
        self.pushButtonPath = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButtonPath.setGeometry(QtCore.QRect(320, 0, 75, 23))
        self.pushButtonPath.setObjectName("pushButtonPath")
        self.pathLabel = QtWidgets.QLabel(parent=self.centralwidget)
        self.pathLabel.setGeometry(QtCore.QRect(330, 30, 47, 13))
        self.pathLabel.setObjectName("pathLabel")
        self.pushButtonStop = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButtonStop.setGeometry(QtCore.QRect(400, 30, 75, 23))
        self.pushButtonStop.setObjectName("pushButtonStop")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 543, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButtonFindDevice.setText(_translate("MainWindow", "Find Device"))
        self.pushButtonConnect.setText(_translate("MainWindow", "Connect"))
        self.textBrowser.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.pushButtonStart.setText(_translate("MainWindow", "Start"))
        self.pushButtonSetup.setText(_translate("MainWindow", "Setup"))
        self.timeEdit.setDisplayFormat(_translate("MainWindow", "mm:ss"))
        self.pushButtonPath.setText(_translate("MainWindow", "Path"))
        self.pathLabel.setText(_translate("MainWindow", "TextLabel"))
        self.pushButtonStop.setText(_translate("MainWindow", "Stop"))
